version: '3.3'

services:
  jobmanager:
    image: flink:1.12.7-scala_2.12
    volumes:
      - ./logs/jobmanager/:/opt/flink/log/
      - ./config/flink-jars/:/opt/flink/connector-lib/
      - ./logs/flink-checkpoints/:/flink-checkpoints
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: rocksdb
        state.checkpoints.dir: file:///flink-checkpoint
  
  taskmanager:
    image: flink:1.12.7-scala_2.12
    volumes:
      - ./logs/taskmanager/:/opt/flink/log/
      - ./logs/flink-checkpoints/:/flink-checkpoints
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        state.backend: rocksdb
        state.checkpoints.dir: file:///flink-checkpoints
