version: '3.3'

services:
  jobmanager:
    image: flink:1.12.7-scala_2.12
    volumes:
      - ./logs/jobmanager/:/opt/flink/log/
      - ./logs/flink-checkpoints/:/flink-checkpoints
      - ./flink-jars/:/opt/flink/connector-lib/
      - ./flink-sql-conf:/opt/flink/sql-conf
    hostname: "jobmanager"
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        state.backend: rocksdb
        state.checkpoints.dir: file:///flink-checkpoint
  
  taskmanager:
    image: flink:1.12.7-scala_2.12
    volumes:
      - ./logs/taskmanager/:/opt/flink/log/
      - ./logs/flink-checkpoints/:/flink-checkpoints
    hostname: "taskmanager"
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - jobmanager:jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        state.backend: rocksdb
        state.checkpoints.dir: file:///flink-checkpoints
        classloader.resolve-order: parent-first

  standalone:
    image: apachepulsar/pulsar:2.8.1
    hostname: "standalone"
    expose:
      - 8080
      - 6650
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && exec bin/pulsar standalone --advertised-address standalone"